=== jwadamson/solarquest/Solarquest/xml/games/Solarquest_Game.dtd
<!ELEMENT game (defaultRuleSet,defaultView,board,cards)>
<!ATTLIST game id ID #REQUIRED>

<!ELEMENT defaultRuleSet (#PCDATA)>

<!ELEMENT defaultView (#PCDATA)>

<!ELEMENT board (node*)>

<!ELEMENT node (nodeType,nodeDest+,startNode?,deed?,action?)>
<!ATTLIST node id ID #REQUIRED>

<!ELEMENT nodeType (#PCDATA)>

<!ELEMENT nodeDest (#PCDATA)>

<!ELEMENT startNode EMPTY>

<!ELEMENT deed (deedPrice,deedGroup,deedRent+,deedFuel*)>

<!ELEMENT deedPrice (#PCDATA)>

<!ELEMENT deedGroup (#PCDATA)>

<!ELEMENT deedRent (#PCDATA)>

<!ELEMENT deedFuel (#PCDATA)>

<!ELEMENT action (actionType,actionValue?)>

<!ELEMENT actionType (#PCDATA)>

<!ELEMENT actionValue (#PCDATA)>

<!ELEMENT cards (card*)>

<!ELEMENT card (action+)>
<!ATTLIST card id ID #REQUIRED>
<!ATTLIST card count CDATA "1">

=== jwadamson/solarquest/Solarquest/xml/games/Solarquest_1985.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE board SYSTEM "Solarquest_Game.dtd">
<game id="Solarquest_1985">
  <defaultRuleSet>Solarquest_1985</defaultRuleSet>
  <defaultView>Solarquest_1985</defaultView>
  <board>
    <node id="Earth">
      <nodeType>solid</nodeType>
      <nodeDest>Well_Earth_1</nodeDest>
      <startNode />
    </node>
    <node id="Well_Earth_1">
      <nodeType>well_pull</nodeType>
      <nodeDest>Earth_Moon</nodeDest>
    </node>
    <node id="Earth_Moon">
      <nodeType>solid</nodeType>
      <nodeDest>Dock_Solar</nodeDest>
      <deed>
        <deedPrice>225</deedPrice>
        <deedGroup>Earth</deedGroup>
        <deedRent>440</deedRent>
        <deedFuel>20</deedFuel>
      </deed>
    </node>
    <node id="Dock_Solar">
      <nodeType>dock</nodeType>
      <nodeDest>Mercury</nodeDest>
      <deed>
        <deedPrice>250</deedPrice>
        <deedGroup>Docks</deedGroup>
        <deedRent>75</deedRent>
        <deedRent>150</deedRent>
        <deedRent>375</deedRent>
        <deedRent>1125</deedRent>
        <deedRent>3940</deedRent>
        <deedFuel>10</deedFuel>
        <deedFuel>15</deedFuel>
        <deedFuel>20</deedFuel>
        <deedFuel>30</deedFuel>
        <deedFuel>40</deedFuel>
      </deed>
    </node>
    <node id="Mercury">
      <nodeType>solid</nodeType>
      <nodeDest>Station_1</nodeDest>
      <deed>
        <deedPrice>375</deedPrice>
        <deedGroup>Mercury</deedGroup>
        <deedRent>1035</deedRent>
        <deedFuel>25</deedFuel>
      </deed>
    </node>
    <node id="Station_1">
      <nodeType>station</nodeType>
      <nodeDest>Space_Earth_Jupiter_1</nodeDest>
      <action>
        <actionType>collect_cash</actionType>
        <actionValue>450</actionValue>
      </action>
    </node>
    <node id="Space_Earth_Jupiter_1">
      <nodeType>space</nodeType>
      <nodeDest>Space_Earth_Jupiter_2</nodeDest>
    </node>
    <node id="Space_Earth_Jupiter_2">
      <nodeType>space</nodeType>
      <nodeDest>Jupiter_Io</nodeDest>
    </node>
    <node id="Jupiter_Io">
      <nodeType>solid</nodeType>
      <nodeDest>Dock_Jupiter</nodeDest>
      <deed>
        <deedPrice>230</deedPrice>
        <deedGroup>Jupiter</deedGroup>
        <deedRent>110</deedRent>
        <deedRent>170</deedRent>
        <deedRent>255</deedRent>
        <deedRent>380</deedRent>
        <deedRent>570</deedRent>
        <deedRent>860</deedRent>
        <deedRent>1290</deedRent>
        <deedRent>1935</deedRent>
        <deedRent>2905</deedRent>
        <deedRent>4360</deedRent>
        <deedRent>6540</deedRent>
        <deedFuel>15</deedFuel>
        <deedFuel>20</deedFuel>
        <deedFuel>25</deedFuel>
        <deedFuel>30</deedFuel>
        <deedFuel>35</deedFuel>
        <deedFuel>40</deedFuel>
        <deedFuel>50</deedFuel>
        <deedFuel>60</deedFuel>
        <deedFuel>75</deedFuel>
        <deedFuel>90</deedFuel>
        <deedFuel>105</deedFuel>
      </deed>
    </node>
    <node id="Dock_Jupiter">
      <nodeType>dock</nodeType>
      <nodeDest>Space_Jupiter_1</nodeDest>
      <deed>
        <deedPrice>150</deedPrice>
        <deedGroup>Docks</deedGroup>
        <deedRent>35</deedRent>
        <deedRent>70</deedRent>
        <deedRent>175</deedRent>
        <deedRent>525</deedRent>
        <deedRent>1840</deedRent>
        <deedFuel>5</deedFuel>
        <deedFuel>5</deedFuel>
        <deedFuel>10</deedFuel>
        <deedFuel>10</deedFuel>
        <deedFuel>20</deedFuel>
      </deed>
    </node>
    <node id="Space_Jupiter_1">
      <nodeType>space</nodeType>
      <nodeDest>Jupiter_Elara</nodeDest>
    </node>
    <node id="Jupiter_Elara">
      <nodeType>solid</nodeType>
      <nodeDest>Jupiter_Callisto</nodeDest>
      <deed>
        <deedPrice>65</deedPrice>
        <deedGroup>Jupiter</deedGroup>
        <deedRent>30</deedRent>
        <deedRent>45</deedRent>
        <deedRent>70</deedRent>
        <deedRent>105</deedRent>
        <deedRent>155</deedRent>
        <deedRent>235</deedRent>
        <deedRent>350</deedRent>
        <deedRent>530</deedRent>
        <deedRent>795</deedRent>
        <deedRent>1195</deedRent>
        <deedRent>1790</deedRent>
        <deedFuel>10</deedFuel>
        <deedFuel>10</deedFuel>
        <deedFuel>15</deedFuel>
        <deedFuel>20</deedFuel>
        <deedFuel>20</deedFuel>
        <deedFuel>25</deedFuel>
        <deedFuel>35</deedFuel>
        <deedFuel>40</deedFuel>
        <deedFuel>50</deedFuel>
        <deedFuel>60</deedFuel>
        <deedFuel>70</deedFuel>
      </deed>
    </node>
    <node id="Jupiter_Callisto">
      <nodeType>solid</nodeType>
      <nodeDest>Station_2</nodeDest>
      <deed>
        <deedPrice>260</deedPrice>
        <deedGroup>Jupiter</deedGroup>
        <deedRent>125</deedRent>
        <deedRent>185</deedRent>
        <deedRent>280</deedRent>
        <deedRent>425</deedRent>
        <deedRent>635</deedRent>
        <deedRent>955</deedRent>
        <deedRent>1435</deedRent>
        <deedRent>2155</deedRent>
        <deedRent>3230</deedRent>
        <deedRent>4850</deedRent>
        <deedRent>7275</deedRent>
        <deedFuel>15</deedFuel>
        <deedFuel>20</deedFuel>
        <deedFuel>25</deedFuel>
        <deedFuel>30</deedFuel>
        <deedFuel>35</deedFuel>
        <deedFuel>40</deedFuel>
        <deedFuel>50</deedFuel>
        <deedFuel>60</deedFuel>
        <deedFuel>75</deedFuel>
        <deedFuel>90</deedFuel>
        <deedFuel>110</deedFuel>
      </deed>
    </node>
    <node id="Station_2">
      <nodeType>station</nodeType>
      <nodeDest>Jupiter_Thebe</nodeDest>
      <action>
        <actionType>collect_cash</actionType>
        <actionValue>200</actionValue>
      </action>
    </node>
    <node id="Jupiter_Thebe">
      <nodeType>solid</nodeType>
      <nodeDest>Space_Jupiter_2</nodeDest>
      <deed>
        <deedPrice>65</deedPrice>
        <deedGroup>Jupiter</deedGroup>
        <deedRent>30</deedRent>
        <deedRent>45</deedRent>
        <deedRent>70</deedRent>
        <deedRent>105</deedRent>
        <deedRent>160</deedRent>
        <deedRent>240</deedRent>
        <deedRent>360</deedRent>
        <deedRent>540</deedRent>
        <deedRent>810</deedRent>
        <deedRent>1220</deedRent>
        <deedRent>1830</deedRent>
        <deedFuel>10</deedFuel>
        <deedFuel>10</deedFuel>
        <deedFuel>15</deedFuel>
        <deedFuel>20</deedFuel>
        <deedFuel>20</deedFuel>
        <deedFuel>25</deedFuel>
        <deedFuel>35</deedFuel>
        <deedFuel>40</deedFuel>
        <deedFuel>50</deedFuel>
        <deedFuel>60</deedFuel>
        <deedFuel>70</deedFuel>
      </deed>
    </node>
    <node id="Space_Jupiter_2">
      <nodeType>space</nodeType>
      <nodeDest>Jupiter_Metis</nodeDest>
    </node>
    <node id="Jupiter_Metis">
      <nodeType>solid</nodeType>
      <nodeDest>Jupiter_Ganymede</nodeDest>
      <deed>
        <deedPrice>50</deedPrice>
        <deedGroup>Jupiter</deedGroup>
        <deedRent>25</deedRent>
        <deedRent>35</deedRent>
        <deedRent>55</deedRent>
        <deedRent>85</deedRent>
        <deedRent>125</deedRent>
        <deedRent>190</deedRent>
        <deedRent>285</deedRent>
        <deedRent>430</deedRent>
        <deedRent>645</deedRent>
        <deedRent>970</deedRent>
        <deedRent>1455</deedRent>
        <deedFuel>10</deedFuel>
        <deedFuel>10</deedFuel>
        <deedFuel>15</deedFuel>
        <deedFuel>15</deedFuel>
        <deedFuel>20</deedFuel>
        <deedFuel>25</deedFuel>
        <deedFuel>30</deedFuel>
        <deedFuel>35</deedFuel>
        <deedFuel>45</deedFuel>
        <deedFuel>55</deedFuel>
        <deedFuel>65</deedFuel>
      </deed>
    </node>
    <node id="Jupiter_Ganymede">
      <nodeType>solid</nodeType>
      <nodeDest>Jupiter_Sinope</nodeDest>
      <nodeDest>Lab_Jupiter</nodeDest>
      <deed>
        <deedPrice>260</deedPrice>
        <deedGroup>Jupiter</deedGroup>
        <deedRent>125</deedRent>
        <deedRent>190</deedRent>
        <deedRent>285</deedRent>
        <deedRent>430</deedRent>
        <deedRent>645</deedRent>
        <deedRent>970</deedRent>
        <deedRent>1460</deedRent>
        <deedRent>2190</deedRent>
        <deedRent>3290</deedRent>
        <deedRent>4935</deedRent>
        <deedRent>7400</deedRent>
        <deedFuel>15</deedFuel>
        <deedFuel>20</deedFuel>
        <deedFuel>25</deedFuel>
        <deedFuel>30</deedFuel>
        <deedFuel>35</deedFuel>
        <deedFuel>45</deedFuel>
        <deedFuel>50</deedFuel>
        <deedFuel>60</deedFuel>
        <deedFuel>75</deedFuel>
        <deedFuel>90</deedFuel>
        <deedFuel>110</deedFuel>
      </deed>
    </node>
    <node id="Lab_Jupiter">
      <nodeType>lab</nodeType>
      <nodeDest>Jupiter_Himalia</nodeDest>
      <deed>
        <deedPrice>250</deedPrice>
        <deedGroup>Labs</deedGroup>
        <deedRent>70</deedRent>
        <deedRent>135</deedRent>
        <deedRent>265</deedRent>
        <deedRent>505</deedRent>
        <deedRent>970</deedRent>
        <deedRent>1865</deedRent>
      </deed>
    </node>
    <node id="Jupiter_Himalia">
      <nodeType>solid</nodeType>
      <nodeDest>Jupiter_Europa</nodeDest>
      <deed>
        <deedPrice>85</deedPrice>
        <deedGroup>Jupiter</deedGroup>
        <deedRent>40</deedRent>
        <deedRent>60</deedRent>
        <deedRent>90</deedRent>
        <deedRent>135</deedRent>
        <deedRent>205</deedRent>
        <deedRent>310</deedRent>
        <deedRent>465</deedRent>
        <deedRent>695</deedRent>
        <deedRent>1045</deedRent>
        <deedRent>1570</deedRent>
        <deedRent>2355</deedRent>
        <deedFuel>10</deedFuel>
