=== jwadamson/solarquest/Solarquest/xml/views/Solarquest_View.dtd
<!ELEMENT view (boardImage,nodeView*,deedGroupView*,cardView*)>
<!ATTLIST view id ID #REQUIRED>

<!ELEMENT boardImage (#PCDATA)>

<!ELEMENT nodeView (displayName,coords)>
<!ATTLIST nodeView for CDATA #REQUIRED>

<!ELEMENT displayName (#PCDATA)>

<!ELEMENT coords (#PCDATA)>

<!ELEMENT deedGroupView (displayName,displayColor)>
<!ATTLIST deedGroupView for CDATA #REQUIRED>

<!ELEMENT displayColor (#PCDATA)>

<!ELEMENT cardView (displayName)>
<!ATTLIST cardView for CDATA #REQUIRED>

=== jwadamson/solarquest/Solarquest/xml/views/Solarquest_1985.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE board SYSTEM "Solarquest_View.dtd">
<view id="Solarquest_1985">
  <boardImage>/images/board1985.png</boardImage>

  <nodeView for="Earth">
    <displayName>Earth</displayName>
    <coords>708 860</coords>
  </nodeView>
  <nodeView for="Well_Earth_1">
    <displayName>Earth Gravity Well</displayName>
    <coords>716 778</coords>
  </nodeView>
  <nodeView for="Earth_Moon">
    <displayName>The Moon</displayName>
    <coords>731 731</coords>
  </nodeView>
  <nodeView for="Dock_Solar">
    <displayName>Solar Space Dock</displayName>
    <coords>747 672</coords>
  </nodeView>
  <nodeView for="Mercury">
    <displayName>Mercury</displayName>
    <coords>787 610</coords>
  </nodeView>
  <nodeView for="Station_1">
    <displayName>Federation Station I</displayName>
    <coords>824 549</coords>
  </nodeView>
  <nodeView for="Space_Earth_Jupiter_1">
    <displayName>Interplanetary Space between Earth and Jupiter</displayName>
    <coords>859 511</coords>
  </nodeView>
  <nodeView for="Space_Earth_Jupiter_2">
    <displayName>Interplanetary Space between Earth and Jupiter</displayName>
    <coords>911 474</coords>
  </nodeView>
  <nodeView for="Jupiter_Io">
    <displayName>Io</displayName>
    <coords>989 449</coords>
  </nodeView>
  <nodeView for="Dock_Jupiter">
    <displayName>Jupiter Space Dock</displayName>
    <coords>1077 426</coords>
  </nodeView>
  <nodeView for="Space_Jupiter_1">
    <displayName>Jupiter Orbit</displayName>
    <coords>1138 391</coords>
  </nodeView>
  <nodeView for="Jupiter_Elara">
    <displayName>Elara</displayName>
    <coords>1184 339</coords>
  </nodeView>
  <nodeView for="Jupiter_Callisto">
    <displayName>Callisto</displayName>
    <coords>1201 251</coords>
  </nodeView>
  <nodeView for="Station_2">
    <displayName>Federation Station II</displayName>
    <coords>1170 169</coords>
  </nodeView>
  <nodeView for="Jupiter_Thebe">
    <displayName>Thebe</displayName>
    <coords>1104 106</coords>
  </nodeView>
  <nodeView for="Space_Jupiter_2">
    <displayName>Jupiter Orbit</displayName>
    <coords>1028 76</coords>
  </nodeView>
  <nodeView for="Jupiter_Metis">
    <displayName>Metis</displayName>
    <coords>944 70</coords>
  </nodeView>
  <nodeView for="Jupiter_Ganymede">
    <displayName>Ganymede</displayName>
    <coords>836 97</coords>
  </nodeView>
  <nodeView for="Lab_Jupiter">
    <displayName>Jupiter Research Lab</displayName>
    <coords>749 168</coords>
  </nodeView>
  <nodeView for="Jupiter_Himalia">
    <displayName>Himalia</displayName>
    <coords>720 233</coords>
  </nodeView>
  <nodeView for="Jupiter_Europa">
    <displayName>Europa</displayName>
    <coords>725 315</coords>
  </nodeView>
  <nodeView for="Jupiter_Amalthea">
    <displayName>Amalthea</displayName>
    <coords>785 401</coords>
  </nodeView>
  <nodeView for="Jupiter_Adrastea">
    <displayName>Adrastea</displayName>
    <coords>873 440</coords>
  </nodeView>
  <nodeView for="Jupiter_Sinope">
    <displayName>Sinope</displayName>
    <coords>750 110</coords>
  </nodeView>
  <nodeView for="Well_Jupiter_1">
    <displayName>Jupiter Gravity Well</displayName>
    <coords>690 110</coords>
  </nodeView>
  <nodeView for="Well_Jupiter_2">
    <displayName>Jupiter Gravity Well</displayName>
    <coords>636 99</coords>
  </nodeView>
  <nodeView for="Well_Jupiter_3">
    <displayName>Jupiter Gravity Well</displayName>
    <coords>585 82</coords>
  </nodeView>
  <nodeView for="Well_Jupiter_4">
    <displayName>Jupiter Gravity Well</displayName>
    <coords>531 59</coords>
  </nodeView>
  <nodeView for="Station_3">
    <displayName>Federation Station III</displayName>
    <coords>469 59</coords>
  </nodeView>
  <nodeView for="Space_Jupiter_Uranus_1">
    <displayName>Interplanetary Space between Jupiter and Uranus</displayName>
    <coords>417 90</coords>
  </nodeView>
  <nodeView for="Uranus_Miranda">
    <displayName>Miranda</displayName>
    <coords>409 161</coords>
  </nodeView>
  <nodeView for="Dock_Uranus">
    <displayName>Uranus Space Dock</displayName>
    <coords>424 237</coords>
  </nodeView>
  <nodeView for="Uranus_Umbriel">
    <displayName>Umbriel</displayName>
    <coords>409 330</coords>
  </nodeView>
  <nodeView for="Uranus_Oberon">
    <displayName>Oberon</displayName>
    <coords>328 392</coords>
  </nodeView>
  <nodeView for="Uranus_Puck">
    <displayName>Puck</displayName>
    <coords>256 362</coords>
  </nodeView>
  <nodeView for="Lab_Uranus">
    <displayName>Uranus Research Lab</displayName>
    <coords>219 302</coords>
  </nodeView>
  <nodeView for="Space_Uranus_1">
    <displayName>Uranus Orbit</displayName>
    <coords>203 241</coords>
  </nodeView>
  <nodeView for="Uranus_Ariel">
    <displayName>Ariel</displayName>
    <coords>196 158</coords>
  </nodeView>
  <nodeView for="Station_4">
    <displayName>Federation Station IV</displayName>
    <coords>231 64</coords>
  </nodeView>
  <nodeView for="Uranus_Titania">
    <displayName>Titania</displayName>
    <coords>368 66</coords>
  </nodeView>
  <nodeView for="Well_Uranus_1">
    <displayName>Uranus Gravity Well</displayName>
    <coords>175 97</coords>
  </nodeView>
  <nodeView for="Well_Uranus_2">
    <displayName>Uranus Gravity Well</displayName>
    <coords>124 71</coords>
  </nodeView>
  <nodeView for="Well_Uranus_3">
    <displayName>Uranus Gravity Well</displayName>
    <coords>81 119</coords>
  </nodeView>
  <nodeView for="Pluto">
    <displayName>Pluto</displayName>
    <coords>64 192</coords>
  </nodeView>
  <nodeView for="Pluto_Charon">
    <displayName>Charon</displayName>
    <coords>57 262</coords>
  </nodeView>
  <nodeView for="Space_Pluto_Mars_1">
    <displayName>Interplenetary Space between Pluto and Mars</displayName>
    <coords>58 329</coords>
  </nodeView>
  <nodeView for="Station_5">
    <displayName>Federation Station V</displayName>
    <coords>67 387</coords>
  </nodeView>
  <nodeView for="Space_Pluto_Mars_2">
    <displayName>Interplenetary Space between Pluto and Mars</displayName>
    <coords>86 448</coords>
  </nodeView>
  <nodeView for="Space_Pluto_Mars_3">
    <displayName>Interplenetary Space between Pluto and Mars</displayName>
    <coords>134 495</coords>
  </nodeView>
  <nodeView for="Mars_Phobos">
    <displayName>Phobos</displayName>
    <coords>208 496</coords>
  </nodeView>
  <nodeView for="Mars">
    <displayName>Mars</displayName>
    <coords>304 512</coords>
  </nodeView>
  <nodeView for="Mars_Deimos">
    <displayName>Deimos</displayName>
    <coords>364 586</coords>
  </nodeView>
  <nodeView for="Space_Mars_Venus_1">
    <displayName>Interplenetary Space between Mars and Venus</displayName>
    <coords>390 636</coords>
  </nodeView>
  <nodeView for="Lab_Venus">
    <displayName>Venus Research Lab</displayName>
    <coords>411 693</coords>
  </nodeView>
  <nodeView for="Venus">
    <displayName>Venus</displayName>
    <coords>471 778</coords>
  </nodeView>
  <nodeView for="Well_Venus_1">
    <displayName>Venus Gravity Well</displayName>
    <coords>524 871</coords>
  </nodeView>
  <nodeView for="Saturn_Phoebe">
    <displayName>Phoebe</displayName>
    <coords>510 944</coords>
  </nodeView>
  <nodeView for="Saturn_Mimas">
    <displayName>Mimas</displayName>
    <coords>412 954</coords>
  </nodeView>
  <nodeView for="Dock_Saturn">
    <displayName>Saturn Space Dock</displayName>
    <coords>331 921</coords>
  </nodeView>
  <nodeView for="Saturn_Dione">
    <displayName>Dione</displayName>
    <coords>242 898</coords>
  </nodeView>
  <nodeView for="Space_Saturn_1">
    <displayName>Saturn Orbit</displayName>
    <coords>149 893</coords>
  </nodeView>
  <nodeView for="Saturn_Iapetus">
    <displayName>Iapetus</displayName>
    <coords>76 945</coords>
  </nodeView>
  <nodeView for="Saturn_Rhea">
    <displayName>Rhea</displayName>
    <coords>82 1032</coords>
  </nodeView>
  <nodeView for="Saturn_Tethys">
    <displayName>Tethys</displayName>
    <coords>136 1098</coords>
  </nodeView>
  <nodeView for="Station_6">
    <displayName>Federation Station VI</displayName>
    <coords>208 1156</coords>
  </nodeView>
  <nodeView for="Saturn_Janus">
    <displayName>Janus</displayName>
    <coords>288 1190</coords>
  </nodeView>
  <nodeView for="Saturn_Enceladus">
    <displayName>Enceladus</displayName>
    <coords>381 1218</coords>
  </nodeView>
  <nodeView for="Lab_Saturn">
    <displayName>Saturn Research Lab</displayName>
    <coords>486 1218</coords>
  </nodeView>
  <nodeView for="Saturn_Hyperion">
    <displayName>Hyperion</displayName>
    <coords>564 1180</coords>
  </nodeView>
  <nodeView for="Saturn_Titan">
    <displayName>Titan</displayName>
    <coords>561 1091</coords>
  </nodeView>
  <nodeView for="Station_7">
    <displayName>Federation Station VII</displayName>
    <coords>505 1014</coords>
  </nodeView>
  <nodeView for="Well_Saturn_1">
    <displayName>Saturn Gravity Well</displayName>
    <coords>597 1139</coords>
  </nodeView>
  <nodeView for="Well_Saturn_2">
    <displayName>Saturn Gravity Well</displayName>
    <coords>641 1097</coords>
  </nodeView>
  <nodeView for="Well_Saturn_3">
    <displayName>Saturn Gravity Well</displayName>
    <coords>694 1069</coords>
  </nodeView>
  <nodeView for="Well_Saturn_4">
    <displayName>Saturn Gravity Well</displayName>
    <coords>751 1055</coords>
  </nodeView>
  <nodeView for="Station_8">
    <displayName>Federation Station VIII</displayName>
    <coords>814 1062</coords>
  </nodeView>
  <nodeView for="Space_Saturn_Neptune_1">
    <displayName>Interplanetary Space between Saturn and Neptune</displayName>
    <coords>868 1080</coords>
  </nodeView>
  <nodeView for="Neptune_Nereid">
